### PR TITLE
Add scholarship info

### PR DESCRIPTION
**Pull request by jennazee**
screen shot 2018-08-22 at 11 15 44 pm

### CODE REVIEW

**Comment by afeld** [comment]
Oops, sorry if I should have waited for @patriciarealini!

**Comment by patriciarealini** [comment]
no biggie, lgtm!

**Comment by patriciarealini** [comment]
@afeld could you revert the copy changes you made? it wasn't clear in the PR that you changed the wording and i don't think it works the way i intended.

**Comment by patriciarealini** [comment]
also @jennazee all the links are broken. 
the application link is sending people to: `https://2018.empirejs.org/%E2%80%9Chttps://goo.gl/forms/HvqoFx6JKFGnCY5i2%E2%80%9D`
the donation link is sending people to: `https://2018.empirejs.org/%E2%80%9Dhttps://ti.to/empirejs/empire-2018%E2%80%9D`
the sponsorship link is sending people to: 
`https://2018.empirejs.org/%E2%80%9Dhttps://2018.empirejs.org/EmpireJS-2018-prospectus.pdf%E2%80%9D`

**Comment by jennazee** [comment]
Ahh hecking "smart" quotes

**Review by patriciarealini — COMMENTED** [review]
@afeld could you revert the copy changes you made? it wasn't clear in the PR that you changed the wording and i don't think it works the way i intended.

**Comment by jennazee** [comment]
Fixed the quotes right to master from the GH UI 😅

**Pull request merged**
